//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;

namespace MassAccountManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Meals = new HashSet<Meal>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string ImagePath { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public string Question { get; set; }
        public string Password { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual ICollection<Meal> Meals { get; set; }
    }
}
